### ISSUE TITLE
Custom URL configurations

### ISSUE THREAD

**Issue by amit-natani** [brunomacedo/ssl-express-www#1]
In our application, we have a dev environment whose URL is not on https. So while applying this library, that will not be working any more.

Is there any option that one can specify the URLs on which this redirection is not needed. 

Thanks

**Comment by brunomacedo** [comment]
Hi @amit-natani,

Sorry, but apply this custom configuration is not an option.
However, thanks for your comment.

I'll work on it. It's really a good thing. You are free to pull request if you find a solution for this. ;)

Thanks!!!

**Comment by raycharius** [comment]
You could check out https://github.com/raycharius/clean-redirect

Does enforce HTTPS and other redirects (like www <==> naked) in one redirect, and is currently maintained, and you can add your own custom logic to it.
